### ISSUE TITLE
Cloudflare error

### ISSUE THREAD

**Issue by huiskesmartijn** [jeroendelfos/scrape_prullenbakvaccin#3]
Currently, the script does not get past the Cloudflare error for me.

undetected_chromedriver.v2 fixes the error for me, which is the updated version of the driver you're currently using. Just to let you know. It doesn't work headless though sadly.

**Comment by jeroendelfos** [comment]
Thanks for the heads up. I'm trying v2 but it doesn't work for me either. Can you try again to see if it works for you?

**Comment by huiskesmartijn** [comment]
I currently have it running without problems, I've attached the code I'm using. Note that its a bit different from yours as I'm not using toaster for notifications, but a telegram API call that sends a message to me.

![image](https://user-images.githubusercontent.com/14930548/119666246-7f1bbb00-be35-11eb-8aec-0886eb21608f.png)

**Comment by jeroendelfos** [comment]
Thanks!

Can you push this to a new branch called 'telegram'?

**Comment by huiskesmartijn** [comment]
I forked the repo and made a new branch called Telegram. If you make a new branch on the main repo, I can make a pull request.

**Comment by huiskesmartijn** [comment]
Currently, the chrome window has to be maximized in order to bypass Cloudflare 100% of the time. Cloudflare doesn't seem to trigger on page reloads or on-site actions (like typing the postal code again and pressing "zoeken"). Using reloads, instead of re-running the whole script again every time, we can probably run this with chrome minimized after passing the first Cloudflare check. I might look at this tomorrow.

**Comment by jeroendelfos** [comment]
Since the site reloads every 60 seconds we could just check for the site content every 60 seconds?

**Comment by huiskesmartijn** [comment]
Indeed, that should work just fine

**Comment by jeroendelfos** [comment]
I just pushed changes doing just that. I will close this issue!
